#include "wad_build.h"
#include <cstdio>

int main(int argc, char** argv) {
    std::vector<uint8_t> w = build_test_wad();

    // With an argument, write the raw WAD bytes to that file (for the hardware
    // smoke test: wrap as WAV, push to the device). With no argument, emit the
    // C header consumed by the ARM build.
    if (argc > 1) {
        FILE* out = fopen(argv[1], "wb");
        if (!out) { fprintf(stderr, "cannot write %s\n", argv[1]); return 1; }
        fwrite(w.data(), 1, w.size(), out);
        fclose(out);
        fprintf(stderr, "wrote %u raw WAD bytes to %s\n", (unsigned)w.size(), argv[1]);
        return 0;
    }

    auto emit = [](const char* name, const char* lenName, const std::vector<uint8_t>& ww) {
        printf("static const uint8_t %s[] = {\n", name);
        for (size_t i = 0; i < ww.size(); ++i) {
            printf("0x%02x,", ww[i]);
            if ((i % 16) == 15) printf("\n");
        }
        printf("\n};\nstatic const uint32_t %s = %u;\n", lenName, (unsigned)ww.size());
    };
    printf("#pragma once\n#include <cstdint>\n");
    printf("// Generated by harness/tools/wad_build. Do not edit by hand.\n");
    emit("kDoomTestWad",    "kDoomTestWadLen",    build_test_wad());
    emit("kDoomBspTestWad", "kDoomBspTestWadLen", build_bsp_test_wad());
    return 0;
}
