#include "wad_build.h"
#include <cstdio>

int main() {
    std::vector<uint8_t> w = build_test_wad();
    printf("#pragma once\n#include <cstdint>\n");
    printf("// Generated by harness/tools/wad_build. Do not edit by hand.\n");
    printf("static const uint8_t kDoomTestWad[] = {\n");
    for (size_t i = 0; i < w.size(); ++i) {
        printf("0x%02x,", w[i]);
        if ((i % 16) == 15) printf("\n");
    }
    printf("\n};\nstatic const uint32_t kDoomTestWadLen = %u;\n", (unsigned)w.size());
    return 0;
}
